# Generated by Django 6.0.6 on 2026-07-01 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('national_ID', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('street', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('user', models.ForeignKey(db_column='user_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='donors', to='users.user')),
            ],
            options={
                'db_table': 'Donors',
            },
        ),
        migrations.CreateModel(
            name='DonorPhone',
            fields=[
                ('pk', models.CompositePrimaryKey('donor', 'phone', blank=True, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('donor', models.ForeignKey(db_column='national_ID', on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='donors.donor')),
            ],
            options={
                'db_table': 'Donor_phone',
            },
        ),
    ]
