# Generated by Django 6.0.6 on 2026-07-01 01:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('units_donated', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('donation_date', models.DateField()),
                ('donor', models.ForeignKey(db_column='national_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='donations', to='donors.donor')),
            ],
            options={
                'db_table': 'Donations',
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('screening_result_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hb_level', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bp', models.CharField(max_length=10)),
                ('hepatitis_b', models.BooleanField()),
                ('hepatitis_c', models.BooleanField()),
                ('hiv', models.BooleanField()),
                ('malaria', models.BooleanField()),
                ('tested_on', models.DateField()),
                ('tested_by', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('Eligible', 'Eligible'), ('Ineligible', 'Ineligible')], max_length=15)),
                ('donation', models.OneToOneField(db_column='donation_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='screening', to='donations.donation')),
            ],
            options={
                'db_table': 'Screenings',
            },
        ),
    ]
