# Generated by Django 6.0.6 on 2026-07-01 01:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('requester_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('requester_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Individual', 'Individual')], max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Requesters',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('urgency', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=15)),
                ('request_date', models.DateField()),
                ('requester', models.ForeignKey(db_column='requester_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to='requests.requester')),
            ],
            options={
                'db_table': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='RequesterPhone',
            fields=[
                ('pk', models.CompositePrimaryKey('requester', 'phone', blank=True, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('requester', models.ForeignKey(db_column='requester_ID', on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='requests.requester')),
            ],
            options={
                'db_table': 'Requester_phone',
            },
        ),
    ]
