# Generated by Django 6.0.6 on 2026-07-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Partial', 'Partial'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=15),
        ),
    ]
