# Generated by Django 6.0.6 on 2026-07-01 01:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('allocation_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('allocated_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('allocation_date', models.DateField()),
                ('allocation_status', models.CharField(choices=[('Pending', 'Pending'), ('Allocated', 'Allocated'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15)),
                ('transport', models.ForeignKey(db_column='transport_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='allocations', to='transport.transport')),
            ],
            options={
                'db_table': 'Allocations',
            },
        ),
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('inventory_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('collection_date', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=15)),
                ('branch', models.ForeignKey(db_column='branch_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='inventories', to='branches.branch')),
            ],
            options={
                'db_table': 'Blood_Inventory',
            },
        ),
    ]
