# Generated by Django 6.0.6 on 2026-07-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodinventory',
            name='allocation',
            field=models.ForeignKey(blank=True, db_column='allocation_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_units', to='inventory.allocation'),
        ),
    ]
