# Generated by Django 6.0.6 on 2026-07-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_bloodinventory_allocation'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodinventory',
            name='request',
            field=models.ForeignKey(blank=True, db_column='request_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_units', to='requests.request'),
        ),
    ]
