# Generated by Django 6.0.6 on 2026-07-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_bloodinventory_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodinventory',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Near Expiry', 'Near Expiry'), ('Expired', 'Expired'), ('Allocated', 'Allocated')], default='Available', max_length=15),
        ),
    ]
