# Generated by Django 6.0.6 on 2026-07-10 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_bloodinventory_status'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='transport',
            field=models.ForeignKey(blank=True, db_column='transport_ID', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='allocations', to='transport.transport'),
        ),
    ]
