# Generated by Django 6.0.6 on 2026-07-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_allocation_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='dispatched_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='received_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
