# Generated by Django 6.0.6 on 2026-07-01 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('transport_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('destination_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Branch', 'Branch')], max_length=15)),
                ('destination_name', models.CharField(max_length=100)),
                ('transport_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15)),
                ('branch', models.ForeignKey(db_column='branch_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='transports', to='branches.branch')),
            ],
            options={
                'db_table': 'Transports',
            },
        ),
    ]
