# Generated by Django 6.0.6 on 2026-07-01 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('branch_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=15)),
                ('user', models.ForeignKey(db_column='user_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='branches', to='users.user')),
            ],
            options={
                'db_table': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='BranchPhone',
            fields=[
                ('pk', models.CompositePrimaryKey('branch', 'phone', blank=True, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('branch', models.ForeignKey(db_column='branch_ID', on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='branches.branch')),
            ],
            options={
                'db_table': 'Branch_phone',
            },
        ),
    ]
