# Generated by Django 6.0.6 on 2026-07-01 01:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile Banking', 'Mobile Banking'), ('Bank Transfer', 'Bank Transfer')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=15)),
                ('allocation', models.ForeignKey(db_column='allocation_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='inventory.allocation')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
    ]
