# Generated by Django 6.0.6 on 2026-07-20 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_allocation_dispatched_time_allocation_received_time'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='allocation',
            field=models.OneToOneField(db_column='allocation_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='payment', to='inventory.allocation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile Banking', 'Mobile Banking'), ('Bank Transfer', 'Bank Transfer')], max_length=20, null=True),
        ),
    ]
