# Generated by Django 6.0.6 on 2026-07-01 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Staff', 'Staff')], max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=15)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('generated_on', models.DateField()),
                ('report_data', models.TextField()),
                ('user', models.ForeignKey(db_column='user_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='reports', to='users.user')),
            ],
            options={
                'db_table': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'phone', blank=True, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('user', models.ForeignKey(db_column='user_ID', on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='users.user')),
            ],
            options={
                'db_table': 'User_phone',
            },
        ),
    ]
